# Generated by Django 4.1 on 2023-01-03 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill_Description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('1', 'Front End'), ('2', 'Back End'), ('3', 'Others')], default='1', max_length=1)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Skill_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('1', 'Front End'), ('2', 'Back End'), ('3', 'Others')], default='1', max_length=1)),
                ('title', models.CharField(max_length=50, verbose_name='タイトル')),
                ('color_code', models.CharField(max_length=20, verbose_name='カラーコード')),
            ],
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
