# Generated by Django 4.1 on 2022-12-24 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_skills_skill_rename_works_work'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
