# Generated by Django 4.1 on 2023-01-07 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_skill_description_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill_description',
            name='category',
        ),
    ]
