# Generated by Django 4.1 on 2022-12-24 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_work_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='image',
            field=models.ImageField(blank=True, upload_to='images', verbose_name='サムネイル'),
        ),
    ]
